<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Back to products_back-image</name>
   <tag></tag>
   <elementGuidId>03d9475e-4095-422c-943a-1df5ed03d20e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='back-to-products']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.back-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d8471041-fcc9-4645-8402-40eed6b386fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAAAXNSR0IArs4c6QAAAJpJREFUOBHV1b8KgCAQB2CN3qvWoKAl6HF6n9aGxh5MMRwuFPxz3t2SywmH3+8GRaX+sOZ1H6dle/ysvcTAHrTWHsbYATwWnAJZcAkkwRiwCW4BUTAFLMIcMAlLgBEsCQLcwUa66hCEyZ1T3wsK+9j9fZ06guEgNyALcwOqMDUADbcGNMPYADJcC2DDuQAPQ0+k+msKX5MImEJePMWUxD8KaN0AAAAASUVORK5CYII=</value>
      <webElementGuid>5c8b0e34-81e7-4400-b62c-562752c097e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>back-image</value>
      <webElementGuid>55ee19d0-6261-43ca-a846-dd8bbbc13129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Go back</value>
      <webElementGuid>4ef0c666-62e3-4fe3-a93f-ca0dcf7db7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;back-to-products&quot;)/img[@class=&quot;back-image&quot;]</value>
      <webElementGuid>46d06ed9-47d9-451c-ac99-37460b7e65fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='back-to-products']/img</value>
      <webElementGuid>569972e8-41d2-40d4-9924-f47938ebff6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Go back']</value>
      <webElementGuid>2498bc90-f132-4fc1-89a3-cfb7978539e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>52df0241-40da-4a1a-a8e8-c8686c8ca46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAAAXNSR0IArs4c6QAAAJpJREFUOBHV1b8KgCAQB2CN3qvWoKAl6HF6n9aGxh5MMRwuFPxz3t2SywmH3+8GRaX+sOZ1H6dle/ysvcTAHrTWHsbYATwWnAJZcAkkwRiwCW4BUTAFLMIcMAlLgBEsCQLcwUa66hCEyZ1T3wsK+9j9fZ06guEgNyALcwOqMDUADbcGNMPYADJcC2DDuQAPQ0+k+msKX5MImEJePMWUxD8KaN0AAAAASUVORK5CYII=' and @alt = 'Go back']</value>
      <webElementGuid>4999a8e9-e353-4224-9bdf-3f0d9088c34b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
